name = "SlabWaveguides"
uuid = "0b0ca172-c548-44c2-b1f0-fffb7d4557e4"
authors = ["Mohamed Kamal AbdElrahman"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
